<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SubscriptionManagement_PaymentsAPI.Domain</RootNamespace>
    <AssemblyName>SubscriptionManagement_PaymentsAPI.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

</Project>
